packages:
  - 'apps/*'
  - 'tooling/*'

catalog:
  "@trpc/client": ^11.0.0-rc.795
  "@trpc/server": ^11.0.0-rc.795
  "@trpc/tanstack-react-query": ^11.0.0-rc.795
  eslint: ^9.19.0
  prettier: ^3.5.1
  prettier-plugin-tailwindcss: ^0.6.11
  "@ianvs/prettier-plugin-sort-imports": ^4.4.1
  typescript: ^5.7.3
  zod: ^3.24.2
