packages:
  - 'apps/*'
  - 'tooling/*'

catalog:
  "@trpc/client": ^11.0.0-rc.798
  "@trpc/server": ^11.0.0-rc.798
  "@trpc/tanstack-react-query": ^11.0.0-rc.798
  "@tanstack/react-query": ^5.66.9
  eslint: ^9.19.0
  prettier: ^3.5.1
  prettier-plugin-tailwindcss: ^0.6.11
  "@ianvs/prettier-plugin-sort-imports": ^4.4.1
  typescript: ^5.7.3
  tailwindcss: ^3.4.14
  zod: ^3.24.2

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
